# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: complex_message.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'complex_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63omplex_message.proto\x12\x0f\x63omplex_message\"\xcf\x01\n\rSimpleMessage\x12\x12\n\nmessage_id\x18\x01 \x01(\x03\x12\x38\n\x04type\x18\x02 \x01(\x0e\x32*.complex_message.SimpleMessage.MessageType\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\x12\r\n\x05\x66lags\x18\x04 \x03(\x05\"P\n\x0bMessageType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07REQUEST\x10\x01\x12\x0c\n\x08RESPONSE\x10\x02\x12\x10\n\x0cNOTIFICATION\x10\x03\x12\x07\n\x03\x41\x43K\x10\x04\"\xae\x01\n\x0fResponseMessage\x12\x1b\n\x13original_message_id\x18\x01 \x01(\x03\x12\x18\n\x10response_content\x18\x02 \x01(\x0c\x12?\n\x06status\x18\x03 \x01(\x0e\x32/.complex_message.ResponseMessage.ResponseStatus\"#\n\x0eResponseStatus\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'complex_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIMPLEMESSAGE']._serialized_start=43
  _globals['_SIMPLEMESSAGE']._serialized_end=250
  _globals['_SIMPLEMESSAGE_MESSAGETYPE']._serialized_start=170
  _globals['_SIMPLEMESSAGE_MESSAGETYPE']._serialized_end=250
  _globals['_RESPONSEMESSAGE']._serialized_start=253
  _globals['_RESPONSEMESSAGE']._serialized_end=427
  _globals['_RESPONSEMESSAGE_RESPONSESTATUS']._serialized_start=392
  _globals['_RESPONSEMESSAGE_RESPONSESTATUS']._serialized_end=427
# @@protoc_insertion_point(module_scope)
