# DataSource Config
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    schema: classpath:db/schema-unit-test-mysql.sql
    data: classpath:db/data-unit-test-mysql.sql
    url: jdbc:p6spy:mysql://localhost:3306/unit_test?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123321
    dbunit:
        schema: unit_test
  main:
    allow-bean-definition-overriding: true
# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples: debug
    org.dbunit: debug
# MyBatis-Plus 配置该演示无
