spring:
  application:
    name: demo-consumer # Spring 应用名
  cloud:
    nacos:
      # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址

server:
  port: 28080 # 服务器端口。默认为 8080
#feign:
#  client:
#  config:
#    default:
#      connectTimeout: 2000
#      readTimeout: 2000

#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 2000
#        readTimeout: 2000

ribbon:
  ConnectTimeout: 2000
  ReadTimeout: 2000
  # 是否所有操作都进行重试
  OkToRetryOnAllOperations: true
  # 同一实例最大重试次数，不包括首次调用
  MaxAutoRetries: 1
  # 重试其他实例的最大重试次数，不包括首次所选的server
  MaxAutoRetriesNextServer: 1