apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: skywalking-ns
spec:
  selector:
    app: elasticsearch
  type: LoadBalancer
  ports:
  - name: outer
    port: 9200
  - name: inner
    port: 9300
    

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: skywalking-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:7.13.4
        imagePullPolicy: IfNotPresent 
        command: ["bash", "-c", "chown -R elasticsearch:elasticsearch /usr/share/elasticsearch/data && exec su elasticsearch docker-entrypoint.sh"]
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1000Mi"
            cpu: "1000m"
        ports:
        - containerPort: 9200
          protocol: TCP
        - containerPort: 9300
          protocol: TCP
        env:
          - name: "discovery.type"
            value: "single-node"
          - name: "ES_JAVA_OPTS"
            value: "-Xms512m -Xmx512m"
        volumeMounts:
          - name: skywalking-data
            mountPath: /usr/share/elasticsearch/data
            subPath: elasticsearch/data
          - name: skywalking-data
            mountPath: /usr/share/elasticsearch/config
            subPath: elasticsearch/config
          - name: skywalking-data
            mountPath: /usr/share/elasticsearch/plugin
            subPath: elasticsearch/plugin
        volumes:
          - name: skywalking-data
            persistentVolumeClaim:
              claimName: skywalking-pvc

