kind: Service
apiVersion: v1
metadata:
  name: reload-example
spec:
  selector:
    app: reload-example
  ports:
  - protocol: TCP
    port: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reload-example
spec:
  selector:
      matchLabels:
        app: reload-example
  replicas: 1
  template:
    metadata:
      labels:
        app: reload-example
    spec:
      containers:
        - name: reload-example
          image: reload-example:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080