kind: Service
apiVersion: v1
metadata:
  name: spring-cloud-kubernetes-example-reload
spec:
  selector:
    app: spring-cloud-kubernetes-example-reload
  ports:
    - protocol: TCP
      port: 8080
  type: LoadBalancer