kind: Service
apiVersion: v1
metadata:
  name:  rabbitmq-svc
spec:
  selector:
    app:  rabbitmq
  type:  LoadBalancer
  ports:
  - name:  rabbitmq15672
    port:  15672
    targetPort:  15672
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.9.1-management
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 15672
