kind: Service
apiVersion: v1
metadata:
  name:  redis-svc
spec:
  selector:
    app:  redis
  type:  LoadBalancer
  ports:
  - name:  redis6379
    port:  6379
    targetPort:  6379
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6.2.5-alpine3.14  # or just image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379