spring:
  application:
    name: client
---
server:
  port: 9001
  ssl:
    enabled: true
    client-auth: need
    key-store: /Users/macuser/IdeaProjects/java-study/advanced/security/ssl-tls-https/two-way-ssl-spring-boot/sh/client.keystore
    key-store-password: 123456
#    key-alias: client
    key-store-type: PKCS12
#    key-store-provider: SUN
    trust-store: /Users/macuser/IdeaProjects/java-study/advanced/security/ssl-tls-https/two-way-ssl-spring-boot/sh/ca.truststore
    trust-store-password: 123456
    trust-store-type: JKS
---
endpoint:
  ms-service: https://127.0.0.1:9002/nt-ms/data