spring:
  application:
    name: server
---
server:
  port: 9002
  ssl:
    enabled: true
    client-auth: need
    key-store: classpath:tomcat.keystore
    key-store-password: 123456
#    key-alias: tomcat
    key-store-type: PKCS12
#    key-store-provider: SUN
    trust-store: classpath:ca.truststore
    trust-store-password: 123456
    trust-store-type: JKS