server:
  port: 8081

spring:
  application:
    name: p6spy-sample
  sleuth:
    enabled: false
    sampler:
      probability: 1
  datasource:
    hikari:
      pool-name: h2
      jdbc-url: jdbc:h2:mem:test-${random.int};DB_CLOSE_DELAY=-1
      username: sa
      password:
      maximum-pool-size: 10
  sql:
    init:
      mode: never
decorator:
  datasource:
    p6spy:
#      custom-appender-class: my.custom.LoggerClass
      enable-logging: true
      log-file: spy.log
#      log-filter:
#        pattern: ''
#      log-format: ''
      logging: slf4j
      multiline: true
      tracing:
        include-parameter-values: true
